name: Coverage report

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change permissions
        run: chmod +x ./gradlew

      - name: Run jacoco
        run: ./gradlew jacocoTestReport

      # generates coverage-report.md and publishes as checkrun
      - name: Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: ${{ github.workspace }}/musiclib/build/coverage/index.html
          coverage_report_name: Coverage
          coverage_report_title: Jacoco tests coverage
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 50
          fail_below_threshold: false
          publish_only_summary: true