name: Coverage report

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Run Jacoco
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/musiclib/build/coverage/index.html ,
            ${{ github.workspace }}/**/musiclib/build/reports/tests.index.html
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 50