name: Generated APK

env:
  # The name of the main module repository
  main_project_module: app

on:

  push:
    branches-ignore:
      - master

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change permissions
        run: chmod +x ./gradlew

      - name: Run gradle tests
        run: ./gradlew test

      - name: Build gradle project
        run: ./gradlew build

      - name: Unit tests results
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-results
          path: ${{ env.main_project_module }}/build/reports/tests/testDebugUnitTest/index.html

      - name: Build APK (Debug)
        run: ./gradlew assembleDebug

      - name: Upload APK (Debug)
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/
